
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstoqueServerImplService", targetNamespace = "http://service/", wsdlLocation = "http://127.0.0.1:5000/estoque?wsdl")
public class EstoqueServerImplService
    extends Service
{

    private final static URL ESTOQUESERVERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESTOQUESERVERIMPLSERVICE_EXCEPTION;
    private final static QName ESTOQUESERVERIMPLSERVICE_QNAME = new QName("http://service/", "EstoqueServerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:5000/estoque?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTOQUESERVERIMPLSERVICE_WSDL_LOCATION = url;
        ESTOQUESERVERIMPLSERVICE_EXCEPTION = e;
    }

    public EstoqueServerImplService() {
        super(__getWsdlLocation(), ESTOQUESERVERIMPLSERVICE_QNAME);
    }

    public EstoqueServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTOQUESERVERIMPLSERVICE_QNAME, features);
    }

    public EstoqueServerImplService(URL wsdlLocation) {
        super(wsdlLocation, ESTOQUESERVERIMPLSERVICE_QNAME);
    }

    public EstoqueServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTOQUESERVERIMPLSERVICE_QNAME, features);
    }

    public EstoqueServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstoqueServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstoqueServer
     */
    @WebEndpoint(name = "EstoqueServerImplPort")
    public EstoqueServer getEstoqueServerImplPort() {
        return super.getPort(new QName("http://service/", "EstoqueServerImplPort"), EstoqueServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstoqueServer
     */
    @WebEndpoint(name = "EstoqueServerImplPort")
    public EstoqueServer getEstoqueServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "EstoqueServerImplPort"), EstoqueServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTOQUESERVERIMPLSERVICE_EXCEPTION!= null) {
            throw ESTOQUESERVERIMPLSERVICE_EXCEPTION;
        }
        return ESTOQUESERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
